### ISSUE TITLE
NameError: name 'scores' is not defined in testing 

### ISSUE THREAD

**Issue by NguyenVanThanhHust** [DirtyHarryLYL/HAKE-Action#11]
I test after training with cmd:
```
python tools/Test_pasta_HICO_DET.py --iteration 2000000 --model HICO_DET_model
```
HICO_DET_model is my model folder.
It returns following error:
```
Traceback (most recent call last):
  File "tools/Test_pasta_HICO_DET.py", line 60, in <module>
    test_net(sess, net, Test_RCNN, output_file)
  File "/home/ubuntu/project/Action_Recognition/HAKE-Action/tools/../lib/models/test_Solver_HICO_DET_pasta.py", line 104, in test_net
    im_detect(sess, net, image_id, Test_RCNN, keys, scores, bboxes, hdet, odet)
NameError: name 'scores' is not defined
```

Does anyone have solution for this error?

**Comment by NguyenVanThanhHust** [comment]
Never mind. I fixed it. But I think authors should update source code.
For anyone who meet the same issue, change line 104, in test_net.py
from 
```
im_detect(sess, net, image_id, Test_RCNN, keys, scores, bboxes, hdet, odet)
```
to 
```
im_detect(sess, net, image_id, Test_RCNN, keys, scores_P, scores_A, scores_L, bboxes, hdet, odet)
```

**Comment by Foruck** [comment]
Thanks for pointing out! It has been fixed in the recent commit.
