### ISSUE TITLE
No such file or directory: './results/fused.csv' and './results/linear_final.csv'.

### ISSUE THREAD

**Issue by geek12138** [DirtyHarryLYL/HAKE-Action#38]
In Image-level HAKE-Action branch, when I run 'python scripts/test.py --pasta-mode linear' in docker. The Error is No such file or directory: './results/fused.csv' and './results/linear_final.csv'. But I don't know where to find these two .csv files.
Thank you.

**Comment by geek12138** [comment]
> In Image-level HAKE-Action branch, when I run 'python scripts/test.py --pasta-mode linear' in docker. The Error is No such file or directory: './results/fused.csv' and './results/linear_final.csv'. But I don't know where to find these two .csv files.
> Thank you.

Traceback (most recent call last):
  File "scripts/fuse.py", line 3, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 4, in <module>
    from . import tkagg  # Paint image to Tk photo blitter extension.
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/tkagg.py", line 5, in <module>
    from six.moves import tkinter as Tk
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 42, in <module>
    raise ImportError, str(msg) + ', please install the python-tk package'
ImportError: No module named _tkinter, please install the python-tk package
Traceback (most recent call last):
  File "scripts/test.py", line 86, in <module>
    prior_info('./results/fused.csv', './data/hico/object80.csv', './data/hico/verb117.csv', 800, 50, './results/linear_final.csv')
  File "/opt/HAKE-Action/scripts/obj_mask.py", line 84, in prior_info
    a1 = np.loadtxt(filename, delimiter = ',', dtype = str,usecols=range(600))
  File "/usr/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 803, in loadtxt
    fh = iter(open(fname, 'U'))
IOError: [Errno 2] No such file or directory: './results/fused.csv'

**Comment by liangxuy** [comment]
`results/fused.csv` is generated by `scripts/fuse.py` and `results/linear_final.csv` is generated by function `prior_info` in `scripts/test.py`. I suggest that you first check whether L85 of `scripts/test.py` (i.e., `python scripts/fuse.py results/Pasta-Linear/Pasta-Linear.csv results/10v-attention/10v-attention.csv results/pairwise.csv results/language-model/language-model.csv`) is successfully executed.

**Comment by geek12138** [comment]
Thanks for your reply, the file has been successfully found and run.
