### ISSUE TITLE
ValueError: None values not supported.

### ISSUE THREAD

**Issue by NguyenVanThanhHust** [DirtyHarryLYL/HAKE-Action#8]
I use pickle 3 instead of cPickle. 
So i change from 
` Trainval_GT       = pickle.load(open(cfg.DATA_DIR + '/' + 'Trainval_GT_all_part.pkl', "rb"))
`
to 
` Trainval_GT       = pickle.load(open(cfg.DATA_DIR + '/' + 'Trainval_GT_all_part.pkl', "rb"), encoding='bytes')
`

Then i got error:
`ValueError: None values not supported.`

This is full error:
`
*************data path:*************
/home/ubuntu/project/Action_Recognition/HAKE-Action/Data
************************************
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

Namespace(Neg_select=60, Pos_augment=15, Restore_flag=5, init_weight=1, iter=1800000, max_iters=2000000, model='test_model', module_update=1, train_continue=2, train_module=2, **{'--data': 0})
WARNING:tensorflow:From /home/ubuntu/project/Action_Recognition/HAKE-Action/tools/../lib/networks/pasta_HICO_DET.py:59: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /home/ubuntu/project/Action_Recognition/HAKE-Action/tools/../lib/models/train_Solver_HICO_DET_pasta.py:272: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From /home/ubuntu/project/Action_Recognition/HAKE-Action/tools/../lib/models/train_Solver_HICO_DET_pasta.py:275: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2020-05-07 11:34:18.152190: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-05-07 11:34:18.592120: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3600000000 Hz
2020-05-07 11:34:18.598650: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55754b0e3470 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-05-07 11:34:18.598733: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-05-07 11:34:18.818668: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-05-07 11:34:19.178313: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-07 11:34:19.178573: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55754b0e0ba0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-05-07 11:34:19.178588: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
2020-05-07 11:34:19.235338: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-07 11:34:19.235578: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:02:00.0
2020-05-07 11:34:19.263674: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-05-07 11:34:19.905750: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-05-07 11:34:20.126609: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-05-07 11:34:20.214744: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-05-07 11:34:21.141719: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-05-07 11:34:21.519181: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-05-07 11:34:22.472666: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-05-07 11:34:22.472987: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-07 11:34:22.473722: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-07 11:34:22.474266: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-05-07 11:34:22.485815: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-05-07 11:34:22.495643: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-05-07 11:34:22.495663: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-05-07 11:34:22.495671: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-05-07 11:34:22.507402: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-07 11:34:22.606499: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-07 11:34:22.654192: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 455 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:02:00.0, compute capability: 7.5)
Solving..., Pos augment = 15, Neg augment = 60, Restore_flag = 5
WARNING:tensorflow:From /home/ubuntu/project/Action_Recognition/HAKE-Action/tools/../lib/models/train_Solver_HICO_DET_pasta.py:55: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.

WARNING:tensorflow:From /home/ubuntu/project/Action_Recognition/HAKE-Action/tools/../lib/networks/pasta_HICO_DET.py:116: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/contrib/layers/python/layers/layers.py:1057: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
WARNING:tensorflow:From /home/ubuntu/project/Action_Recognition/HAKE-Action/tools/../lib/networks/pasta_HICO_DET.py:166: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
WARNING:tensorflow:From /home/ubuntu/project/Action_Recognition/HAKE-Action/tools/../lib/networks/pasta_HICO_DET.py:179: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
WARNING:tensorflow:From /home/ubuntu/project/Action_Recognition/HAKE-Action/tools/../lib/networks/pasta_HICO_DET.py:179: calling crop_and_resize_v1 (from tensorflow.python.ops.image_ops_impl) with box_ind is deprecated and will be removed in a future version.
Instructions for updating:
box_ind is deprecated, use box_indices instead
WARNING:tensorflow:From /home/ubuntu/project/Action_Recognition/HAKE-Action/tools/../lib/networks/pasta_HICO_DET.py:389: The name tf.trainable_variables is deprecated. Please use tf.compat.v1.trainable_variables instead.

WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/ops/nn_impl.py:183: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From /home/ubuntu/project/Action_Recognition/HAKE-Action/tools/../lib/networks/pasta_HICO_DET.py:399: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

WARNING:tensorflow:From /home/ubuntu/project/Action_Recognition/HAKE-Action/tools/../lib/networks/pasta_HICO_DET.py:402: The name tf.summary.merge_all is deprecated. Please use tf.compat.v1.summary.merge_all instead.

WARNING:tensorflow:From /home/ubuntu/project/Action_Recognition/HAKE-Action/tools/../lib/networks/pasta_HICO_DET.py:403: The name tf.summary.merge is deprecated. Please use tf.compat.v1.summary.merge instead.

WARNING:tensorflow:From /home/ubuntu/project/Action_Recognition/HAKE-Action/tools/../lib/models/train_Solver_HICO_DET_pasta.py:71: The name tf.train.MomentumOptimizer is deprecated. Please use tf.compat.v1.train.MomentumOptimizer instead.

resnet_v1_50/block2/unit_1/bottleneck_v1/shortcut/weights:0
resnet_v1_50/block2/unit_1/bottleneck_v1/conv1/weights:0
resnet_v1_50/block2/unit_1/bottleneck_v1/conv2/weights:0
resnet_v1_50/block2/unit_1/bottleneck_v1/conv3/weights:0
resnet_v1_50/block2/unit_2/bottleneck_v1/conv1/weights:0
resnet_v1_50/block2/unit_2/bottleneck_v1/conv2/weights:0
resnet_v1_50/block2/unit_2/bottleneck_v1/conv3/weights:0
resnet_v1_50/block2/unit_3/bottleneck_v1/conv1/weights:0
resnet_v1_50/block2/unit_3/bottleneck_v1/conv2/weights:0
resnet_v1_50/block2/unit_3/bottleneck_v1/conv3/weights:0
resnet_v1_50/block2/unit_4/bottleneck_v1/conv1/weights:0
resnet_v1_50/block2/unit_4/bottleneck_v1/conv2/weights:0
resnet_v1_50/block2/unit_4/bottleneck_v1/conv3/weights:0
resnet_v1_50/block3/unit_1/bottleneck_v1/shortcut/weights:0
resnet_v1_50/block3/unit_1/bottleneck_v1/conv1/weights:0
resnet_v1_50/block3/unit_1/bottleneck_v1/conv2/weights:0
resnet_v1_50/block3/unit_1/bottleneck_v1/conv3/weights:0
resnet_v1_50/block3/unit_2/bottleneck_v1/conv1/weights:0
resnet_v1_50/block3/unit_2/bottleneck_v1/conv2/weights:0
resnet_v1_50/block3/unit_2/bottleneck_v1/conv3/weights:0
resnet_v1_50/block3/unit_3/bottleneck_v1/conv1/weights:0
resnet_v1_50/block3/unit_3/bottleneck_v1/conv2/weights:0
resnet_v1_50/block3/unit_3/bottleneck_v1/conv3/weights:0
resnet_v1_50/block3/unit_4/bottleneck_v1/conv1/weights:0
resnet_v1_50/block3/unit_4/bottleneck_v1/conv2/weights:0
resnet_v1_50/block3/unit_4/bottleneck_v1/conv3/weights:0
resnet_v1_50/block3/unit_5/bottleneck_v1/conv1/weights:0
resnet_v1_50/block3/unit_5/bottleneck_v1/conv2/weights:0
resnet_v1_50/block3/unit_5/bottleneck_v1/conv3/weights:0
resnet_v1_50/block3/unit_6/bottleneck_v1/conv1/weights:0
resnet_v1_50/block3/unit_6/bottleneck_v1/conv2/weights:0
resnet_v1_50/block3/unit_6/bottleneck_v1/conv3/weights:0
resnet_v1_50/block4/unit_1/bottleneck_v1/shortcut/weights:0
resnet_v1_50/block4/unit_1/bottleneck_v1/conv1/weights:0
resnet_v1_50/block4/unit_1/bottleneck_v1/conv2/weights:0
resnet_v1_50/block4/unit_1/bottleneck_v1/conv3/weights:0
resnet_v1_50/block4/unit_2/bottleneck_v1/conv1/weights:0
resnet_v1_50/block4/unit_2/bottleneck_v1/conv2/weights:0
resnet_v1_50/block4/unit_2/bottleneck_v1/conv3/weights:0
resnet_v1_50/block4/unit_3/bottleneck_v1/conv1/weights:0
resnet_v1_50/block4/unit_3/bottleneck_v1/conv2/weights:0
resnet_v1_50/block4/unit_3/bottleneck_v1/conv3/weights:0
resnet_v1_50/block5/unit_1/bottleneck_v1/shortcut/weights:0
resnet_v1_50/block5/unit_1/bottleneck_v1/conv1/weights:0
resnet_v1_50/block5/unit_1/bottleneck_v1/conv2/weights:0
resnet_v1_50/block5/unit_1/bottleneck_v1/conv3/weights:0
resnet_v1_50/block5/unit_2/bottleneck_v1/conv1/weights:0
resnet_v1_50/block5/unit_2/bottleneck_v1/conv2/weights:0
resnet_v1_50/block5/unit_2/bottleneck_v1/conv3/weights:0
resnet_v1_50/block5/unit_3/bottleneck_v1/conv1/weights:0
resnet_v1_50/block5/unit_3/bottleneck_v1/conv2/weights:0
resnet_v1_50/block5/unit_3/bottleneck_v1/conv3/weights:0
pasta_classification/cls_pasta_0/fully_connected/weights:0
pasta_classification/cls_pasta_0/fully_connected/biases:0
pasta_classification/cls_pasta_0/fully_connected_1/weights:0
pasta_classification/cls_pasta_0/fully_connected_1/biases:0
pasta_classification/cls_pasta_0/fully_connected_2/weights:0
pasta_classification/cls_pasta_0/fully_connected_2/biases:0
pasta_classification/cls_pasta_1/fully_connected/weights:0
pasta_classification/cls_pasta_1/fully_connected/biases:0
pasta_classification/cls_pasta_1/fully_connected_1/weights:0
pasta_classification/cls_pasta_1/fully_connected_1/biases:0
pasta_classification/cls_pasta_1/fully_connected_2/weights:0
pasta_classification/cls_pasta_1/fully_connected_2/biases:0
pasta_classification/cls_pasta_2/fully_connected/weights:0
pasta_classification/cls_pasta_2/fully_connected/biases:0
pasta_classification/cls_pasta_2/fully_connected_1/weights:0
pasta_classification/cls_pasta_2/fully_connected_1/biases:0
pasta_classification/cls_pasta_2/fully_connected_2/weights:0
pasta_classification/cls_pasta_2/fully_connected_2/biases:0
pasta_classification/cls_pasta_3/fully_connected/weights:0
pasta_classification/cls_pasta_3/fully_connected/biases:0
pasta_classification/cls_pasta_3/fully_connected_1/weights:0
pasta_classification/cls_pasta_3/fully_connected_1/biases:0
pasta_classification/cls_pasta_3/fully_connected_2/weights:0
pasta_classification/cls_pasta_3/fully_connected_2/biases:0
pasta_classification/cls_pasta_4/fully_connected/weights:0
pasta_classification/cls_pasta_4/fully_connected/biases:0
pasta_classification/cls_pasta_4/fully_connected_1/weights:0
pasta_classification/cls_pasta_4/fully_connected_1/biases:0
pasta_classification/cls_pasta_4/fully_connected_2/weights:0
pasta_classification/cls_pasta_4/fully_connected_2/biases:0
pasta_classification/cls_pasta_5/fully_connected/weights:0
pasta_classification/cls_pasta_5/fully_connected/biases:0
pasta_classification/cls_pasta_5/fully_connected_1/weights:0
pasta_classification/cls_pasta_5/fully_connected_1/biases:0
pasta_classification/cls_pasta_5/fully_connected_2/weights:0
pasta_classification/cls_pasta_5/fully_connected_2/biases:0
vec_classification/fully_connected/weights:0
vec_classification/fully_connected/biases:0
vec_classification/fully_connected_1/weights:0
vec_classification/fully_connected_1/biases:0
vec_classification/fully_connected_2/weights:0
vec_classification/fully_connected_2/biases:0
vec_attention/fully_connected/weights:0
vec_attention/fully_connected/biases:0
verb_classification/fully_connected/weights:0
verb_classification/fully_connected/biases:0
region_classification/cls_score_P/weights:0
region_classification/cls_score_P/biases:0
region_classification/cls_score_A/weights:0
region_classification/cls_score_A/biases:0
region_classification/fully_connected/weights:0
region_classification/fully_connected/biases:0
region_classification/cls_score_L/weights:0
region_classification/cls_score_L/biases:0
Traceback (most recent call last):
  File "tools/Train_pasta_HICO_DET.py", line 93, in <module>
    train_net(net, Trainval_GT, Trainval_N, output_dir, tb_dir, args.Pos_augment, args.Neg_select, args.Restore_flag, weight, max_iters=args.max_iters)
  File "/home/ubuntu/project/Action_Recognition/HAKE-Action/tools/../lib/models/train_Solver_HICO_DET_pasta.py", line 279, in train_net
    sw.train_model(sess, max_iters)
  File "/home/ubuntu/project/Action_Recognition/HAKE-Action/tools/../lib/models/train_Solver_HICO_DET_pasta.py", line 193, in train_model
    lr, train_op = self.construct_graph(sess)
  File "/home/ubuntu/project/Action_Recognition/HAKE-Action/tools/../lib/models/train_Solver_HICO_DET_pasta.py", line 76, in construct_graph
    capped_gvs     = [(tf.clip_by_norm(grad, 1.), var) for grad, var in grads_and_vars]
  File "/home/ubuntu/project/Action_Recognition/HAKE-Action/tools/../lib/models/train_Solver_HICO_DET_pasta.py", line 76, in <listcomp>
    capped_gvs     = [(tf.clip_by_norm(grad, 1.), var) for grad, var in grads_and_vars]
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/ops/clip_ops.py", line 166, in clip_by_norm
    t.values if isinstance(t, ops.IndexedSlices) else t, name="t")
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1184, in convert_to_tensor
    return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1242, in convert_to_tensor_v2
    as_ref=False)
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1297, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/framework/constant_op.py", line 286, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/framework/constant_op.py", line 227, in constant
    allow_broadcast=True)
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/framework/constant_op.py", line 265, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/framework/tensor_util.py", line 437, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.
`

OS: Ubuntu18.04
Cuda 10.2
CUdnn 7

Does anyone get this error? 
Do you have any idea how to fix it?

**Comment by Foruck** [comment]
Thanks for using our code!
This is caused by a typo in lib/models/train_Solver_HICO_DET_pasta.py, and we have fixed it in the latest commit.

**Comment by NguyenVanThanhHust** [comment]
Thank you. I can train it now.
