### ISSUE TITLE
Not found error

### ISSUE THREAD

**Issue by NguyenVanThanhHust** [DirtyHarryLYL/HAKE-Action#9]
When i run cmd `python tools/Train_pasta_HICO_DET.py --data 0 --init_weight 1 --train_module 2 --num_iteration 2000000 --model test_model`, I didn't found resnet_101 model as in your code. So I download model from pretrained model from tensorflow zoo. I download resnet_101_coco, but I see present 50 layers. So I download resnet_50 and meet below error. 
`
Restoring model snapshots from /home/ubuntu/project/Action_Recognition/HAKE-Action/Weights/faster_rcnn_resnet50_coco_2018_01_28/model.ckpt
WARNING:tensorflow:From /home/ubuntu/project/Action_Recognition/HAKE-Action/tools/../lib/models/train_Solver_HICO_DET_pasta.py:118: The name tf.model_variables is deprecated. Please use tf.compat.v1.model_variables instead.

2020-05-08 18:20:31.852477: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key resnet_v1_50/block1/unit_1/bottleneck_v1/conv1/BatchNorm/beta not found in checkpoint
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found: Key resnet_v1_50/block1/unit_1/bottleneck_v1/conv1/BatchNorm/beta not found in checkpoint
	 [[{{node save_1/RestoreV2}}]]
  (1) Not found: Key resnet_v1_50/block1/unit_1/bottleneck_v1/conv1/BatchNorm/beta not found in checkpoint
	 [[{{node save_1/RestoreV2}}]]
	 [[save_1/RestoreV2/_441]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 1290, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found: Key resnet_v1_50/block1/unit_1/bottleneck_v1/conv1/BatchNorm/beta not found in checkpoint
	 [[node save_1/RestoreV2 (defined at /home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
  (1) Not found: Key resnet_v1_50/block1/unit_1/bottleneck_v1/conv1/BatchNorm/beta not found in checkpoint
	 [[node save_1/RestoreV2 (defined at /home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
	 [[save_1/RestoreV2/_441]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'save_1/RestoreV2':
  File "tools/Train_pasta_HICO_DET.py", line 93, in <module>
    train_net(net, Trainval_GT, Trainval_N, output_dir, tb_dir, args.Pos_augment, args.Neg_select, args.Restore_flag, weight, max_iters=args.max_iters)
  File "/home/ubuntu/project/Action_Recognition/HAKE-Action/tools/../lib/models/train_Solver_HICO_DET_pasta.py", line 279, in train_net
    sw.train_model(sess, max_iters)
  File "/home/ubuntu/project/Action_Recognition/HAKE-Action/tools/../lib/models/train_Solver_HICO_DET_pasta.py", line 201, in train_model
    self.from_snapshot(sess)      # load from snapshot
  File "/home/ubuntu/project/Action_Recognition/HAKE-Action/tools/../lib/models/train_Solver_HICO_DET_pasta.py", line 141, in from_snapshot
    self.saver_restore = tf.train.Saver(saver_t)
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 828, in __init__
    self.build()
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 878, in _build
    build_restore=build_restore)
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_io_ops.py", line 1696, in restore_v2
    name=name)
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 1300, in restore
    names_to_keys = object_graph_key_mapping(save_path)
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 1618, in object_graph_key_mapping
    object_graph_string = reader.get_tensor(trackable.OBJECT_GRAPH_PROTO_KEY)
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 915, in get_tensor
    return CheckpointReader_GetTensor(self, compat.as_bytes(tensor_str))
tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/Train_pasta_HICO_DET.py", line 93, in <module>
    train_net(net, Trainval_GT, Trainval_N, output_dir, tb_dir, args.Pos_augment, args.Neg_select, args.Restore_flag, weight, max_iters=args.max_iters)
  File "/home/ubuntu/project/Action_Recognition/HAKE-Action/tools/../lib/models/train_Solver_HICO_DET_pasta.py", line 279, in train_net
    sw.train_model(sess, max_iters)
  File "/home/ubuntu/project/Action_Recognition/HAKE-Action/tools/../lib/models/train_Solver_HICO_DET_pasta.py", line 201, in train_model
    self.from_snapshot(sess)      # load from snapshot
  File "/home/ubuntu/project/Action_Recognition/HAKE-Action/tools/../lib/models/train_Solver_HICO_DET_pasta.py", line 142, in from_snapshot
    self.saver_restore.restore(sess, self.pretrained_model)
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 1306, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

2 root error(s) found.
  (0) Not found: Key resnet_v1_50/block1/unit_1/bottleneck_v1/conv1/BatchNorm/beta not found in checkpoint
	 [[node save_1/RestoreV2 (defined at /home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
  (1) Not found: Key resnet_v1_50/block1/unit_1/bottleneck_v1/conv1/BatchNorm/beta not found in checkpoint
	 [[node save_1/RestoreV2 (defined at /home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
	 [[save_1/RestoreV2/_441]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'save_1/RestoreV2':
  File "tools/Train_pasta_HICO_DET.py", line 93, in <module>
    train_net(net, Trainval_GT, Trainval_N, output_dir, tb_dir, args.Pos_augment, args.Neg_select, args.Restore_flag, weight, max_iters=args.max_iters)
  File "/home/ubuntu/project/Action_Recognition/HAKE-Action/tools/../lib/models/train_Solver_HICO_DET_pasta.py", line 279, in train_net
    sw.train_model(sess, max_iters)
  File "/home/ubuntu/project/Action_Recognition/HAKE-Action/tools/../lib/models/train_Solver_HICO_DET_pasta.py", line 201, in train_model
    self.from_snapshot(sess)      # load from snapshot
  File "/home/ubuntu/project/Action_Recognition/HAKE-Action/tools/../lib/models/train_Solver_HICO_DET_pasta.py", line 141, in from_snapshot
    self.saver_restore = tf.train.Saver(saver_t)
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 828, in __init__
    self.build()
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 878, in _build
    build_restore=build_restore)
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_io_ops.py", line 1696, in restore_v2
    name=name)
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/ubuntu/anaconda3/envs/act_reg/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

`
Can you check which model should I use with that cmd? Tks you.

**Comment by NguyenVanThanhHust** [comment]
Closed. It is model from tensorflow zoo.

**Comment by Foruck** [comment]
We have fixed the checkpoint path in the latest commit. Try to run the following command to download the checkpoints.

```shell
python script/Download_data.py 1IbR4kiWgLF8seaKjOMmwaHs0Bfwl5Dq1 Weights/res50_faster_rcnn_iter_1190000.ckpt.data-00000-of-00001
python script/Download_data.py 1-DbfEloN4c2JaCEMnexaWAsSc4MDlZJx Weights/res50_faster_rcnn_iter_1190000.ckpt.index
python script/Download_data.py 1vc5d3OwCtMtRgXq3Pj4_twpK4x3kjgT0 Weights/res50_faster_rcnn_iter_1190000.ckpt.meta
```.

**Comment by NguyenVanThanhHust** [comment]
Ok, this issue is closed. I meet another issue.  I think you should update this and version of python that you're using to Readme.md to avoid other people open the same issue.
I suppose that you using python2.
Tks.
